{% set name = "ncvis" %}
{% set version = "1.5.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 886ec878d3dc533d0bc461b2897e4b25e7420c154d061c9e34c70596a950a274

build:
  number: 0
  skip: true  # [py==27]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux and not aarch64]
  host:
    - llvm-openmp  # [osx]
    - libgomp      # [linux and not aarch64]
    - python
    - pip
    - numpy
    - cython
  run:
    - llvm-openmp  # [osx]
    - libgomp      # [linux and not aarch64]
    - python
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  files:
    - test.py
    - test_init.py
  requires:
    - pytest
  commands:
    - python test_init.py
    - pytest test.py

about:
  home: https://github.com/stat-ml/ncvis
  license_file:
    - LICENSE
    - lib/hnswlib/LICENSE
    - lib/pcg-cpp/LICENSE-APACHE.txt
  license: MIT
  license_family: MIT
  summary: Efficient solution for data visualization

  description: |
    NCVis is an efficient solution for data visualization and dimensionality
    reduction. It uses  HNSW <https://github.com/nmslib/hnswlib> to quickly
    construct the nearest neighbors graph and a parallel (batched) approach
    to build its embedding. Efficient random sampling is achieved via 
    PCGRandom <https://github.com/imneme/pcg-cpp>.
  doc_url: https://github.com/stat-ml/ncvis-examples
  dev_url: https://github.com/stat-ml/ncvis

extra:
  recipe-maintainers:
    - alartum
