{% set name = "ncvis" %}
{% set version = "1.5.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: deeb8b2437ff39829261fd86419c00a648a114ff9885af7a8ba11daf76a7bbb7

build:
  number: 3
  skip: true  # [py==27]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux and not aarch64]
  host:
    - llvm-openmp  # [osx]
    - libgomp      # [linux and not aarch64]
    - python
    - pip
    - numpy
    - cython
    - pybind11
  run:
    - llvm-openmp  # [osx]
    - libgomp      # [linux and not aarch64]
    - python
    - scipy

test:
  files:
    - test.py
    - test_init.py
  requires:
    - pytest
  commands:
    - python test_init.py
    # Sometimes the OpenMP doesn't work correctly on CI
    # We will rely on the tests for parallelism from the original repo
    - pytest -k "not test_parallel" test.py

about:
  home: https://github.com/stat-ml/ncvis
  license_file:
    - LICENSE
    - lib/hnswlib/LICENSE
    - lib/pcg-cpp/LICENSE-APACHE.txt
  license: MIT
  license_family: MIT
  summary: Efficient solution for data visualization

  description: |
    NCVis is an efficient solution for data visualization and dimensionality
    reduction. It uses  HNSW <https://github.com/nmslib/hnswlib> to quickly
    construct the nearest neighbors graph and a parallel (batched) approach
    to build its embedding. Efficient random sampling is achieved via 
    PCGRandom <https://github.com/imneme/pcg-cpp>.
  doc_url: https://github.com/stat-ml/ncvis-examples
  dev_url: https://github.com/stat-ml/ncvis

extra:
  recipe-maintainers:
    - alartum
